<?php
/**
 * @var $this \Mestrona\CommonBlocks\Block\StoreInformation
 */
?>
<div class="store-contact">
    <span class="store-contact-phone">
        <a href="tel:<?php echo $this->escapeHtml($this->getPhone()); ?>"><?php echo $this->escapeHtml($this->getPhone()); ?></a>
    </span>
    <span class="store-contact-email">
        <a href="mailto:<?php echo $this->escapeHtml($this->getEMail()); ?>"><?php echo $this->escapeHtml($this->getEMail()); ?></a>
    </span>
</div>
